### ISSUE TITLE
Explain build_fnmatch.py:24

### ISSUE THREAD

**Issue by nils-werner** [wolever/python-cffi-example#1]
Sorry to bother you on the issue tracker like this... Can you explain why you need to `set_source` **and** `cdef` `fname.h`?

**Comment by wolever** [comment]
Not a problem! Under the hood, CFFI generates and compiles an extension module (a .c file) which wrap C calls to the functions defined in `cdef` with Python-friendly functions. But we still need the `set_source("#include <fnmath.h>")` in `set_soruce`, otherwise the C compiler would complain that `fnmatch(…)` is undefined while it's building the extension module.

I've started an explanation (although still _incredibly_ incomplete) of how CFFI works which should hopefully address this: https://github.com/wolever/python-cffi-example/tree/how-cffi-works#how-cffi-works
